 include:
 - board: seeeduino_xiao_ble
   shield: sirius19_dongle
   snippet: studio-rpc-usb-uart
 - board: seeeduino_xiao_ble
   shield: sirius19_left
 - board: seeeduino_xiao_ble
   shield: sirius19_right
 - board: seeeduino_xiao_ble
   shield: settings_reset
